### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '.snakemake/log

### ISSUE THREAD

**Issue by Rohit-Satyam** [basf/riboCleaner#1]
When trying to run the riboCleaner workflow I get the following error. Can you help me how can I handle this error?

```
docker run -v ${PWD}/inputs:/analysis/inputs     -v ${PWD}/results:/analysis/results     -v ${PWD}/.snakemake:/analysis/.snakemake     basfcontainers/ribocleaner     snakemake --cores 1 --report results/riboCleaner_full_report.zip -pr all
```

```
Traceback (most recent call last):
  File "/usr/local/bin/snakemake", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/snakemake/__init__.py", line 2654, in main
    success = snakemake(
  File "/usr/local/lib/python3.8/dist-packages/snakemake/__init__.py", line 528, in snakemake
    logger.setup_logfile()
  File "/usr/local/lib/python3.8/dist-packages/snakemake/logging.py", line 308, in setup_logfile
    os.makedirs(os.path.join(".snakemake", "log"), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '.snakemake/log'
```

**Comment by Rohit-Satyam** [comment]
Changing the `.sanakemake` and `results` directory permission using `chmod 777 ` worked. However, not it presents a new error:

```
docker run -v ${PWD}/inputs:/analysis/inputs     -v ${PWD}/results:/analysis/results     -v ${PWD}/.snakemake:/analysis/.snakemake     basfcontainers/ribocleaner     snakemake --cores 1 --report results/riboCleaner_full_report.zip -pr all
Building DAG of jobs...
Creating report...
WorkflowError:
File results/01_rDNA_identification/all_rdna_models.txt marked for report but does not exist.
  File "/usr/local/lib/python3.8/dist-packages/snakemake/report/__init__.py", line 634, in auto_report
```
